### ISSUE TITLE
找不到有些类

### ISSUE THREAD

**Issue by OharaRinneY** [NeverBehave/telegram-recorder#1]
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    client(UpdateStatusRequest(offline=True))
NameError: name 'UpdateStatusRequest' is not defined
 ![](https://i.loli.net/2018/05/13/5af7ba2b0adf6.jpg)

**Comment by yiheng0** [comment]
￼

**Comment by NeverBehave** [comment]
3722643 已经修订，感谢反馈
